### ISSUE TITLE
Add to the setup how to run a MySQL server using Apptainer

### ISSUE THREAD

**Issue by michmx** [hsf-training/hsf-training-databases-basics#4]
Some people may be working on institutional clusters, where Docker is not available / not allowed. 

Apptainer provides instances to start a MySQL server that can be used to follow the training module. It can point as well to our training on instances (https://hsf-training.github.io/hsf-training-singularity-webpage/08-instances/index.html)

**Comment by panta-123** [comment]
May be we can use the instruction here: https://www.hpc.iastate.edu/guides/containers/mysql-server
This is best one i got for mysql with singularity.
