### ISSUE TITLE
Use sql alchemy for python mysql tutorial 

### ISSUE THREAD

**Issue by panta-123** [hsf-training/hsf-training-databases-basics#6]
using mysql.connector, we are just executing the same sql commands .
I think its better to have tutorial of mysql and python using sql alchemy.
@michmx , what do you think ?

**Comment by michmx** [comment]
Yes, good idea. Maybe just mention at the beginning of the chapter that `mysql.connector` is available if you want, and there is this other option SQL alchemy.
